### ISSUE TITLE
.js file missing

### ISSUE THREAD

**Issue by marchultquist** [breakerh/hammer-splinterlands-bot#15]
I just noticed after downloading 0.9.3 new version and running the battle collection .js that in your install instructions it says to run "node combine.js" but in your code repo combine.js does not exsist... ?

**Comment by breakerh** [comment]
Fixed in [V 0.9.5](https://github.com/breakerh/hammer-splinterlands-bot/releases/tag/V0.9.5)

**Comment by marchultquist** [comment]
No worries, we all get busy 👍 Thank-you for looking at the issue!! I will download the latest update and see how it goes 👍
